# Dockerfile.basic
FROM eclipse-temurin:17-jdk

# metadata
LABEL maintainer="Your Name <you@example.com>"
ENV SPRING_PROFILES_ACTIVE=prod

# create app directory
WORKDIR /app

# copy jar (build artifact must exist)
COPY target/spring-petclinic-*.jar app.jar

# optional: add a non-root user
RUN useradd -ms /bin/false appuser && chown appuser /app/app.jar
USER appuser

EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]
CMD ["--server.port=8080"]
