FROM jenkins/jenkins:lts

USER root

# Install dependencies (Maven, curl, gnupg, etc.)
RUN apt-get update && apt-get install -y \
    unzip \
    curl \
    gnupg \
    lsb-release \
    maven \
    ca-certificates

# Install HashiCorp repo + Terraform
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg \
    | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
    https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
    > /etc/apt/sources.list.d/hashicorp.list && \
    apt-get update && apt-get install -y terraform

# Install Docker CLI (Debian Bookworm / no apt-key)
RUN curl -fsSL https://download.docker.com/linux/debian/gpg \
    | gpg --dearmor -o /usr/share/keyrings/docker.gpg && \
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] \
    https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list && \
    apt-get update && apt-get install -y docker-ce-cli

# Add Jenkins user to Docker group
RUN groupadd -f docker && usermod -aG docker jenkins

USER jenkins

